/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BasicProp {
        "creditCard": string;
        "paymentFlow": string;
    }
    interface BasicRendering {
    }
    interface BasicState {
    }
    interface ComponentSample {
    }
}
declare global {
    interface HTMLBasicPropElement extends Components.BasicProp, HTMLStencilElement {
    }
    var HTMLBasicPropElement: {
        prototype: HTMLBasicPropElement;
        new (): HTMLBasicPropElement;
    };
    interface HTMLBasicRenderingElement extends Components.BasicRendering, HTMLStencilElement {
    }
    var HTMLBasicRenderingElement: {
        prototype: HTMLBasicRenderingElement;
        new (): HTMLBasicRenderingElement;
    };
    interface HTMLBasicStateElement extends Components.BasicState, HTMLStencilElement {
    }
    var HTMLBasicStateElement: {
        prototype: HTMLBasicStateElement;
        new (): HTMLBasicStateElement;
    };
    interface HTMLComponentSampleElement extends Components.ComponentSample, HTMLStencilElement {
    }
    var HTMLComponentSampleElement: {
        prototype: HTMLComponentSampleElement;
        new (): HTMLComponentSampleElement;
    };
    interface HTMLElementTagNameMap {
        "basic-prop": HTMLBasicPropElement;
        "basic-rendering": HTMLBasicRenderingElement;
        "basic-state": HTMLBasicStateElement;
        "component-sample": HTMLComponentSampleElement;
    }
}
declare namespace LocalJSX {
    interface BasicProp {
        "creditCard": string;
        "paymentFlow": string;
    }
    interface BasicRendering {
    }
    interface BasicState {
    }
    interface ComponentSample {
    }
    interface IntrinsicElements {
        "basic-prop": BasicProp;
        "basic-rendering": BasicRendering;
        "basic-state": BasicState;
        "component-sample": ComponentSample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "basic-prop": LocalJSX.BasicProp & JSXBase.HTMLAttributes<HTMLBasicPropElement>;
            "basic-rendering": LocalJSX.BasicRendering & JSXBase.HTMLAttributes<HTMLBasicRenderingElement>;
            "basic-state": LocalJSX.BasicState & JSXBase.HTMLAttributes<HTMLBasicStateElement>;
            "component-sample": LocalJSX.ComponentSample & JSXBase.HTMLAttributes<HTMLComponentSampleElement>;
        }
    }
}
